name: CI/CD Pipeline

on:
  push:
    branches:
      - deploy  # Trigger on pushes to the deploy branch
  pull_request:
    branches:
      - deploy  # Trigger on pull requests to the deploy branch

jobs:
  # Job for testing, building, and deploying
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, ctype, fileinfo, json, openssl, pdo_mysql, pdo_sqlite, tokenizer, xml
          coverage: none

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js dependencies
        run: npm install

      - name: Build React assets
        run: npm run build

#      - name: Run tests (optional)
#        run: php artisan test # You can run your tests here

      - name: Deploy to DigitalOcean
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DO_SERVER_IP: ${{ secrets.DO_SERVER_IP }}
        run: |
          # Configure SSH
          mkdir -p ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DO_SERVER_IP >> ~/.ssh/known_hosts

          # Deploy Laravel application to DigitalOcean
          ssh -o StrictHostKeyChecking=no root@$DO_SERVER_IP << 'EOF'
            cd /var/www
            git clone https://github.com/aviroez/laravel-gym.git laravel-gym || (cd laravel-gym && git pull)
            cd laravel-gym
            git pull origin deploy || exit 1
            composer install --no-dev --optimize-autoloader || exit 1
            php artisan migrate --force || exit 1
            npm install || exit 1
            npm run build || exit 1
            php artisan config:cache || exit 1
            php artisan route:cache || exit 1
            sudo service apache2 restart || exit 1
          EOF
