name: Push Branch Deploy Pipeline

on:
  push:
    branches:
      - deploy  # Trigger on pushes to the deploy branch

jobs:
  # Job for testing, building, and deploying
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DO_SERVER_IP: ${{ secrets.DO_SERVER_IP }}
        run: |
          # Configure SSH
          mkdir -p ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DO_SERVER_IP >> ~/.ssh/known_hosts

          # Deploy Laravel application to DigitalOcean
          ssh -o StrictHostKeyChecking=no deployer@$DO_SERVER_IP << 'EOF'
            cd /var/www/html
            git clone https://github.com/aviroez/laravel-gym.git laravel-gym || (cd laravel-gym && git pull)
            cd laravel-gym
            git pull origin deploy || exit 1
            composer install --optimize-autoloader || exit 1
            php artisan migrate --force || exit 1
            npm install || exit 1
            npm run build || exit 1
            php artisan config:cache || exit 1
            php artisan route:cache || exit 1
            sudo service apache2 restart || exit 1
          EOF
